services:
  - type: web
    name: n8n
    env: docker
    region: oregon
    plan: free
    branch: main
    numInstances: 1
    healthCheckPath: /
    envVars:
      - key: DB_TYPE
        value: postgresdb
      - key: DB_POSTGRESDB_HOST
        value: dpg-d1av9u8dl3ps73e4j2tg-a
      - key: DB_POSTGRESDB_PORT
        value: 5432
      - key: DB_POSTGRESDB_DATABASE
        value: n8n_db_7v8d
      - key: DB_POSTGRESDB_USER
        value: n8n_db_7v8d_user
      - key: DB_POSTGRESDB_PASSWORD
        value: 3id39vhniI1Gll1VTdpbLNLHpE8WL2tm
      - key: DB_POSTGRESDB_SCHEMA
        value: public
      - key: WEBHOOK_URL
        value: https://your-n8n-app.onrender.com/
      - key: N8N_ENCRYPTION_KEY
        value: your_strong_random_key_here
      - key: GENERIC_TIMEZONE
        value: America/Sao_Paulo
      - key: TZ
        value: America/Sao_Paulo
      - key: N8N_LOG_LEVEL
        value: info
      - key: EXECUTIONS_DATA_PRUNE
        value: true
      - key: EXECUTIONS_DATA_MAX_AGE
        value: 168
      - key: EXECUTIONS_DATA_SAVE_ON_ERROR
        value: all
      - key: EXECUTIONS_DATA_SAVE_ON_SUCCESS
        value: none
      - key: EXECUTIONS_DATA_SAVE_ON_PROGRESS
        value: false
    
  - key: EXECUTIONS_DATA_SAVE_MANUAL_EXECUTIONS
        value: false
      - key: N8N_RUNNERS_ENABLED
        value: true
      - key: N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS
        value: true
